/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.AssuntoControllerApi();
  });

  describe('(package)', function() {
    describe('AssuntoControllerApi', function() {
      describe('createUsingPOST', function() {
        it('should call createUsingPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for createUsingPOST call and complete the assertions
          /*
          var assuntoDTO = new ApiDocumentation.AssuntoDTOInput();
          assuntoDTO.descricao = "";
          assuntoDTO.flAtivo = "";

          instance.createUsingPOST(assuntoDTO, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ApiDocumentation.AssuntoDTOOutput);
            expect(data.descricao).to.be.a('string');
            expect(data.descricao).to.be("");
            expect(data.dtCadastro).to.be.a(Date);
            expect(data.dtCadastro).to.be(new Date());
            expect(data.flAtivo).to.be.a('string');
            expect(data.flAtivo).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteUsingDELETE', function() {
        it('should call deleteUsingDELETE successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteUsingDELETE call
          /*
          var id = 789;

          instance.deleteUsingDELETE(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findAllUsingGET', function() {
        it('should call findAllUsingGET successfully', function(done) {
          // TODO: uncomment findAllUsingGET call and complete the assertions
          /*

          instance.findAllUsingGET(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(ApiDocumentation.AssuntoDTOOutput);
              expect(data.descricao).to.be.a('string');
              expect(data.descricao).to.be("");
              expect(data.dtCadastro).to.be.a(Date);
              expect(data.dtCadastro).to.be(new Date());
              expect(data.flAtivo).to.be.a('string');
              expect(data.flAtivo).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('findUsingGET', function() {
        it('should call findUsingGET successfully', function(done) {
          // TODO: uncomment, update parameter values for findUsingGET call and complete the assertions
          /*
          var id = 789;

          instance.findUsingGET(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(ApiDocumentation.AssuntoDTOOutput);
            expect(data.descricao).to.be.a('string');
            expect(data.descricao).to.be("");
            expect(data.dtCadastro).to.be.a(Date);
            expect(data.dtCadastro).to.be(new Date());
            expect(data.flAtivo).to.be.a('string');
            expect(data.flAtivo).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateUsingPUT', function() {
        it('should call updateUsingPUT successfully', function(done) {
          // TODO: uncomment, update parameter values for updateUsingPUT call
          /*
          var assuntoDTO = new ApiDocumentation.AssuntoDTOInput();
          assuntoDTO.descricao = "";
          assuntoDTO.flAtivo = "";
          var id = 789;

          instance.updateUsingPUT(assuntoDTO, id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
