/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Assunto', 'model/AssuntoDTOInput', 'model/AssuntoDTOOutput', 'model/Interessado', 'model/InteressadoDTOInput', 'model/InteressadoDTOOutput', 'model/ProcessoDTOInput', 'model/ProcessoDTOOutput', 'api/AssuntoControllerApi', 'api/InteressadoControllerApi', 'api/ProcessoControllerApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Assunto'), require('./model/AssuntoDTOInput'), require('./model/AssuntoDTOOutput'), require('./model/Interessado'), require('./model/InteressadoDTOInput'), require('./model/InteressadoDTOOutput'), require('./model/ProcessoDTOInput'), require('./model/ProcessoDTOOutput'), require('./api/AssuntoControllerApi'), require('./api/InteressadoControllerApi'), require('./api/ProcessoControllerApi'));
  }
}(function(ApiClient, Assunto, AssuntoDTOInput, AssuntoDTOOutput, Interessado, InteressadoDTOInput, InteressadoDTOOutput, ProcessoDTOInput, ProcessoDTOOutput, AssuntoControllerApi, InteressadoControllerApi, ProcessoControllerApi) {
  'use strict';

  /**
   * Api_Documentation.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var ApiDocumentation = require('index'); // See note below*.
   * var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new ApiDocumentation.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new ApiDocumentation.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new ApiDocumentation.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Assunto model constructor.
     * @property {module:model/Assunto}
     */
    Assunto: Assunto,
    /**
     * The AssuntoDTOInput model constructor.
     * @property {module:model/AssuntoDTOInput}
     */
    AssuntoDTOInput: AssuntoDTOInput,
    /**
     * The AssuntoDTOOutput model constructor.
     * @property {module:model/AssuntoDTOOutput}
     */
    AssuntoDTOOutput: AssuntoDTOOutput,
    /**
     * The Interessado model constructor.
     * @property {module:model/Interessado}
     */
    Interessado: Interessado,
    /**
     * The InteressadoDTOInput model constructor.
     * @property {module:model/InteressadoDTOInput}
     */
    InteressadoDTOInput: InteressadoDTOInput,
    /**
     * The InteressadoDTOOutput model constructor.
     * @property {module:model/InteressadoDTOOutput}
     */
    InteressadoDTOOutput: InteressadoDTOOutput,
    /**
     * The ProcessoDTOInput model constructor.
     * @property {module:model/ProcessoDTOInput}
     */
    ProcessoDTOInput: ProcessoDTOInput,
    /**
     * The ProcessoDTOOutput model constructor.
     * @property {module:model/ProcessoDTOOutput}
     */
    ProcessoDTOOutput: ProcessoDTOOutput,
    /**
     * The AssuntoControllerApi service constructor.
     * @property {module:api/AssuntoControllerApi}
     */
    AssuntoControllerApi: AssuntoControllerApi,
    /**
     * The InteressadoControllerApi service constructor.
     * @property {module:api/InteressadoControllerApi}
     */
    InteressadoControllerApi: InteressadoControllerApi,
    /**
     * The ProcessoControllerApi service constructor.
     * @property {module:api/ProcessoControllerApi}
     */
    ProcessoControllerApi: ProcessoControllerApi
  };

  return exports;
}));
