/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * AssuntoDTOOutput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-01T19:08:42.632Z")
public class AssuntoDTOOutput {
  @SerializedName("descricao")
  private String descricao = null;

  @SerializedName("dtCadastro")
  private LocalDate dtCadastro = null;

  @SerializedName("flAtivo")
  private String flAtivo = null;

  @SerializedName("id")
  private Long id = null;

  public AssuntoDTOOutput descricao(String descricao) {
    this.descricao = descricao;
    return this;
  }

   /**
   * Get descricao
   * @return descricao
  **/
  @ApiModelProperty(value = "")
  public String getDescricao() {
    return descricao;
  }

  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

  public AssuntoDTOOutput dtCadastro(LocalDate dtCadastro) {
    this.dtCadastro = dtCadastro;
    return this;
  }

   /**
   * Get dtCadastro
   * @return dtCadastro
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDtCadastro() {
    return dtCadastro;
  }

  public void setDtCadastro(LocalDate dtCadastro) {
    this.dtCadastro = dtCadastro;
  }

  public AssuntoDTOOutput flAtivo(String flAtivo) {
    this.flAtivo = flAtivo;
    return this;
  }

   /**
   * Get flAtivo
   * @return flAtivo
  **/
  @ApiModelProperty(value = "")
  public String getFlAtivo() {
    return flAtivo;
  }

  public void setFlAtivo(String flAtivo) {
    this.flAtivo = flAtivo;
  }

  public AssuntoDTOOutput id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssuntoDTOOutput assuntoDTOOutput = (AssuntoDTOOutput) o;
    return Objects.equals(this.descricao, assuntoDTOOutput.descricao) &&
        Objects.equals(this.dtCadastro, assuntoDTOOutput.dtCadastro) &&
        Objects.equals(this.flAtivo, assuntoDTOOutput.flAtivo) &&
        Objects.equals(this.id, assuntoDTOOutput.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descricao, dtCadastro, flAtivo, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssuntoDTOOutput {\n");
    
    sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
    sb.append("    dtCadastro: ").append(toIndentedString(dtCadastro)).append("\n");
    sb.append("    flAtivo: ").append(toIndentedString(flAtivo)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

