/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InteressadoDTOInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-01T19:08:42.632Z")
public class InteressadoDTOInput {
  @SerializedName("dtNascimento")
  private String dtNascimento = null;

  @SerializedName("flAtivo")
  private String flAtivo = null;

  @SerializedName("nmInteressado")
  private String nmInteressado = null;

  @SerializedName("nuIdentificacao")
  private String nuIdentificacao = null;

  public InteressadoDTOInput dtNascimento(String dtNascimento) {
    this.dtNascimento = dtNascimento;
    return this;
  }

   /**
   * Get dtNascimento
   * @return dtNascimento
  **/
  @ApiModelProperty(required = true, value = "")
  public String getDtNascimento() {
    return dtNascimento;
  }

  public void setDtNascimento(String dtNascimento) {
    this.dtNascimento = dtNascimento;
  }

  public InteressadoDTOInput flAtivo(String flAtivo) {
    this.flAtivo = flAtivo;
    return this;
  }

   /**
   * Get flAtivo
   * @return flAtivo
  **/
  @ApiModelProperty(value = "")
  public String getFlAtivo() {
    return flAtivo;
  }

  public void setFlAtivo(String flAtivo) {
    this.flAtivo = flAtivo;
  }

  public InteressadoDTOInput nmInteressado(String nmInteressado) {
    this.nmInteressado = nmInteressado;
    return this;
  }

   /**
   * Get nmInteressado
   * @return nmInteressado
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNmInteressado() {
    return nmInteressado;
  }

  public void setNmInteressado(String nmInteressado) {
    this.nmInteressado = nmInteressado;
  }

  public InteressadoDTOInput nuIdentificacao(String nuIdentificacao) {
    this.nuIdentificacao = nuIdentificacao;
    return this;
  }

   /**
   * Get nuIdentificacao
   * @return nuIdentificacao
  **/
  @ApiModelProperty(required = true, value = "")
  public String getNuIdentificacao() {
    return nuIdentificacao;
  }

  public void setNuIdentificacao(String nuIdentificacao) {
    this.nuIdentificacao = nuIdentificacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InteressadoDTOInput interessadoDTOInput = (InteressadoDTOInput) o;
    return Objects.equals(this.dtNascimento, interessadoDTOInput.dtNascimento) &&
        Objects.equals(this.flAtivo, interessadoDTOInput.flAtivo) &&
        Objects.equals(this.nmInteressado, interessadoDTOInput.nmInteressado) &&
        Objects.equals(this.nuIdentificacao, interessadoDTOInput.nuIdentificacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dtNascimento, flAtivo, nmInteressado, nuIdentificacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InteressadoDTOInput {\n");
    
    sb.append("    dtNascimento: ").append(toIndentedString(dtNascimento)).append("\n");
    sb.append("    flAtivo: ").append(toIndentedString(flAtivo)).append("\n");
    sb.append("    nmInteressado: ").append(toIndentedString(nmInteressado)).append("\n");
    sb.append("    nuIdentificacao: ").append(toIndentedString(nuIdentificacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

