/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ProcessoDTOOutput', function() {
      beforeEach(function() {
        instance = new ApiDocumentation.ProcessoDTOOutput();
      });

      it('should create an instance of ProcessoDTOOutput', function() {
        // TODO: update the code to test ProcessoDTOOutput
        expect(instance).to.be.a(ApiDocumentation.ProcessoDTOOutput);
      });

      it('should have the property cdAssunto (base name: "cdAssunto")', function() {
        // TODO: update the code to test the property cdAssunto
        expect(instance).to.have.property('cdAssunto');
        // expect(instance.cdAssunto).to.be(expectedValueLiteral);
      });

      it('should have the property cdInteressado (base name: "cdInteressado")', function() {
        // TODO: update the code to test the property cdInteressado
        expect(instance).to.have.property('cdInteressado');
        // expect(instance.cdInteressado).to.be(expectedValueLiteral);
      });

      it('should have the property chaveProcesso (base name: "chaveProcesso")', function() {
        // TODO: update the code to test the property chaveProcesso
        expect(instance).to.have.property('chaveProcesso');
        // expect(instance.chaveProcesso).to.be(expectedValueLiteral);
      });

      it('should have the property descricao (base name: "descricao")', function() {
        // TODO: update the code to test the property descricao
        expect(instance).to.have.property('descricao');
        // expect(instance.descricao).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property nuAno (base name: "nuAno")', function() {
        // TODO: update the code to test the property nuAno
        expect(instance).to.have.property('nuAno');
        // expect(instance.nuAno).to.be(expectedValueLiteral);
      });

      it('should have the property nuProcesso (base name: "nuProcesso")', function() {
        // TODO: update the code to test the property nuProcesso
        expect(instance).to.have.property('nuProcesso');
        // expect(instance.nuProcesso).to.be(expectedValueLiteral);
      });

      it('should have the property sgOrgaoSetor (base name: "sgOrgaoSetor")', function() {
        // TODO: update the code to test the property sgOrgaoSetor
        expect(instance).to.have.property('sgOrgaoSetor');
        // expect(instance.sgOrgaoSetor).to.be(expectedValueLiteral);
      });

    });
  });

}));
