/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AssuntoDTOInput;
import io.swagger.client.model.AssuntoDTOOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssuntoControllerApi
 */
@Ignore
public class AssuntoControllerApiTest {

    private final AssuntoControllerApi api = new AssuntoControllerApi();

    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUsingPOSTTest() throws ApiException {
        AssuntoDTOInput assuntoDTO = null;
        AssuntoDTOOutput response = api.createUsingPOST(assuntoDTO);

        // TODO: test validations
    }
    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllUsingGETTest() throws ApiException {
        List<AssuntoDTOOutput> response = api.findAllUsingGET();

        // TODO: test validations
    }
    
    /**
     * find
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findUsingGETTest() throws ApiException {
        Long id = null;
        AssuntoDTOOutput response = api.findUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPUTTest() throws ApiException {
        AssuntoDTOInput assuntoDTO = null;
        Long id = null;
        api.updateUsingPUT(assuntoDTO, id);

        // TODO: test validations
    }
    
}
