/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.InteressadoDTOInput;
import io.swagger.client.model.InteressadoDTOOutput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InteressadoControllerApi
 */
@Ignore
public class InteressadoControllerApiTest {

    private final InteressadoControllerApi api = new InteressadoControllerApi();

    
    /**
     * create
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUsingPOST1Test() throws ApiException {
        InteressadoDTOInput interessadoDTO = null;
        InteressadoDTOOutput response = api.createUsingPOST1(interessadoDTO);

        // TODO: test validations
    }
    
    /**
     * delete
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUsingDELETE1Test() throws ApiException {
        Long id = null;
        api.deleteUsingDELETE1(id);

        // TODO: test validations
    }
    
    /**
     * findAll
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllUsingGET1Test() throws ApiException {
        String nuIdentificacao = null;
        List<InteressadoDTOOutput> response = api.findAllUsingGET1(nuIdentificacao);

        // TODO: test validations
    }
    
    /**
     * find
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findUsingGET1Test() throws ApiException {
        Long id = null;
        InteressadoDTOOutput response = api.findUsingGET1(id);

        // TODO: test validations
    }
    
    /**
     * update
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUsingPUT1Test() throws ApiException {
        Long id = null;
        InteressadoDTOInput interessadoDTO = null;
        api.updateUsingPUT1(id, interessadoDTO);

        // TODO: test validations
    }
    
}
