/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AssuntoDTOInput', 'model/AssuntoDTOOutput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AssuntoDTOInput'), require('../model/AssuntoDTOOutput'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.AssuntoControllerApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.AssuntoDTOInput, root.ApiDocumentation.AssuntoDTOOutput);
  }
}(this, function(ApiClient, AssuntoDTOInput, AssuntoDTOOutput) {
  'use strict';

  /**
   * AssuntoController service.
   * @module api/AssuntoControllerApi
   * @version 1.0
   */

  /**
   * Constructs a new AssuntoControllerApi. 
   * @alias module:api/AssuntoControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createUsingPOST operation.
     * @callback module:api/AssuntoControllerApi~createUsingPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssuntoDTOOutput} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create
     * @param {module:model/AssuntoDTOInput} assuntoDTO assuntoDTO
     * @param {module:api/AssuntoControllerApi~createUsingPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssuntoDTOOutput}
     */
    this.createUsingPOST = function(assuntoDTO, callback) {
      var postBody = assuntoDTO;

      // verify the required parameter 'assuntoDTO' is set
      if (assuntoDTO === undefined || assuntoDTO === null) {
        throw new Error("Missing the required parameter 'assuntoDTO' when calling createUsingPOST");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = AssuntoDTOOutput;

      return this.apiClient.callApi(
        '/v1/assuntos', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUsingDELETE operation.
     * @callback module:api/AssuntoControllerApi~deleteUsingDELETECallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete
     * @param {Number} id id
     * @param {module:api/AssuntoControllerApi~deleteUsingDELETECallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteUsingDELETE = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUsingDELETE");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v1/assuntos/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findAllUsingGET operation.
     * @callback module:api/AssuntoControllerApi~findAllUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/AssuntoDTOOutput>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findAll
     * @param {module:api/AssuntoControllerApi~findAllUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/AssuntoDTOOutput>}
     */
    this.findAllUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [AssuntoDTOOutput];

      return this.apiClient.callApi(
        '/v1/assuntos', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findUsingGET operation.
     * @callback module:api/AssuntoControllerApi~findUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AssuntoDTOOutput} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * find
     * @param {Number} id id
     * @param {module:api/AssuntoControllerApi~findUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AssuntoDTOOutput}
     */
    this.findUsingGET = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findUsingGET");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = AssuntoDTOOutput;

      return this.apiClient.callApi(
        '/v1/assuntos/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUsingPUT operation.
     * @callback module:api/AssuntoControllerApi~updateUsingPUTCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update
     * @param {module:model/AssuntoDTOInput} assuntoDTO assuntoDTO
     * @param {Number} id id
     * @param {module:api/AssuntoControllerApi~updateUsingPUTCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateUsingPUT = function(assuntoDTO, id, callback) {
      var postBody = assuntoDTO;

      // verify the required parameter 'assuntoDTO' is set
      if (assuntoDTO === undefined || assuntoDTO === null) {
        throw new Error("Missing the required parameter 'assuntoDTO' when calling updateUsingPUT");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUsingPUT");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v1/assuntos/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
