/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProcessoDTOInput', 'model/ProcessoDTOOutput'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ProcessoDTOInput'), require('../model/ProcessoDTOOutput'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.ProcessoControllerApi = factory(root.ApiDocumentation.ApiClient, root.ApiDocumentation.ProcessoDTOInput, root.ApiDocumentation.ProcessoDTOOutput);
  }
}(this, function(ApiClient, ProcessoDTOInput, ProcessoDTOOutput) {
  'use strict';

  /**
   * ProcessoController service.
   * @module api/ProcessoControllerApi
   * @version 1.0
   */

  /**
   * Constructs a new ProcessoControllerApi. 
   * @alias module:api/ProcessoControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createUsingPOST2 operation.
     * @callback module:api/ProcessoControllerApi~createUsingPOST2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/ProcessoDTOOutput} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * create
     * @param {module:model/ProcessoDTOInput} processoDTO processoDTO
     * @param {module:api/ProcessoControllerApi~createUsingPOST2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProcessoDTOOutput}
     */
    this.createUsingPOST2 = function(processoDTO, callback) {
      var postBody = processoDTO;

      // verify the required parameter 'processoDTO' is set
      if (processoDTO === undefined || processoDTO === null) {
        throw new Error("Missing the required parameter 'processoDTO' when calling createUsingPOST2");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ProcessoDTOOutput;

      return this.apiClient.callApi(
        '/v1/processos', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteUsingDELETE2 operation.
     * @callback module:api/ProcessoControllerApi~deleteUsingDELETE2Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * delete
     * @param {Number} id id
     * @param {module:api/ProcessoControllerApi~deleteUsingDELETE2Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteUsingDELETE2 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteUsingDELETE2");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v1/processos/{id}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findAllUsingGET2 operation.
     * @callback module:api/ProcessoControllerApi~findAllUsingGET2Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ProcessoDTOOutput>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * findAll
     * @param {Object} opts Optional parameters
     * @param {String} opts.cdAssuntoDescricao cd_assunto_descricao
     * @param {String} opts.chaveProcesso chave_processo
     * @param {Number} opts.nuProcesso nu_processo
     * @param {module:api/ProcessoControllerApi~findAllUsingGET2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ProcessoDTOOutput>}
     */
    this.findAllUsingGET2 = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'cd_assunto_descricao': opts['cdAssuntoDescricao'],
        'chave_processo': opts['chaveProcesso'],
        'nu_processo': opts['nuProcesso'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [ProcessoDTOOutput];

      return this.apiClient.callApi(
        '/v1/processos', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the findUsingGET2 operation.
     * @callback module:api/ProcessoControllerApi~findUsingGET2Callback
     * @param {String} error Error message, if any.
     * @param {module:model/ProcessoDTOOutput} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * find
     * @param {Number} id id
     * @param {module:api/ProcessoControllerApi~findUsingGET2Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ProcessoDTOOutput}
     */
    this.findUsingGET2 = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling findUsingGET2");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = ProcessoDTOOutput;

      return this.apiClient.callApi(
        '/v1/processos/{id}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateUsingPUT2 operation.
     * @callback module:api/ProcessoControllerApi~updateUsingPUT2Callback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * update
     * @param {Number} id id
     * @param {module:model/ProcessoDTOInput} processoDTO processoDTO
     * @param {module:api/ProcessoControllerApi~updateUsingPUT2Callback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateUsingPUT2 = function(id, processoDTO, callback) {
      var postBody = processoDTO;

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling updateUsingPUT2");
      }

      // verify the required parameter 'processoDTO' is set
      if (processoDTO === undefined || processoDTO === null) {
        throw new Error("Missing the required parameter 'processoDTO' when calling updateUsingPUT2");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/v1/processos/{id}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
