/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.InteressadoDTOOutput = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InteressadoDTOOutput model module.
   * @module model/InteressadoDTOOutput
   * @version 1.0
   */

  /**
   * Constructs a new <code>InteressadoDTOOutput</code>.
   * @alias module:model/InteressadoDTOOutput
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InteressadoDTOOutput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InteressadoDTOOutput} obj Optional instance to populate.
   * @return {module:model/InteressadoDTOOutput} The populated <code>InteressadoDTOOutput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dtNascimento'))
        obj.dtNascimento = ApiClient.convertToType(data['dtNascimento'], 'Date');
      if (data.hasOwnProperty('flAtivo'))
        obj.flAtivo = ApiClient.convertToType(data['flAtivo'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('nmInteressado'))
        obj.nmInteressado = ApiClient.convertToType(data['nmInteressado'], 'String');
      if (data.hasOwnProperty('nuIdentificacao'))
        obj.nuIdentificacao = ApiClient.convertToType(data['nuIdentificacao'], 'String');
    }
    return obj;
  }

  /**
   * @member {Date} dtNascimento
   */
  exports.prototype.dtNascimento = undefined;

  /**
   * @member {String} flAtivo
   */
  exports.prototype.flAtivo = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} nmInteressado
   */
  exports.prototype.nmInteressado = undefined;

  /**
   * @member {String} nuIdentificacao
   */
  exports.prototype.nuIdentificacao = undefined;


  return exports;

}));
