/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.InteressadoDTOInput = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The InteressadoDTOInput model module.
   * @module model/InteressadoDTOInput
   * @version 1.0
   */

  /**
   * Constructs a new <code>InteressadoDTOInput</code>.
   * @alias module:model/InteressadoDTOInput
   * @class
   * @param dtNascimento {String} 
   * @param nmInteressado {String} 
   * @param nuIdentificacao {String} 
   */
  var exports = function(dtNascimento, nmInteressado, nuIdentificacao) {
    this.dtNascimento = dtNascimento;
    this.nmInteressado = nmInteressado;
    this.nuIdentificacao = nuIdentificacao;
  };

  /**
   * Constructs a <code>InteressadoDTOInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InteressadoDTOInput} obj Optional instance to populate.
   * @return {module:model/InteressadoDTOInput} The populated <code>InteressadoDTOInput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('dtNascimento'))
        obj.dtNascimento = ApiClient.convertToType(data['dtNascimento'], 'String');
      if (data.hasOwnProperty('flAtivo'))
        obj.flAtivo = ApiClient.convertToType(data['flAtivo'], 'String');
      if (data.hasOwnProperty('nmInteressado'))
        obj.nmInteressado = ApiClient.convertToType(data['nmInteressado'], 'String');
      if (data.hasOwnProperty('nuIdentificacao'))
        obj.nuIdentificacao = ApiClient.convertToType(data['nuIdentificacao'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} dtNascimento
   */
  exports.prototype.dtNascimento = undefined;

  /**
   * @member {String} flAtivo
   */
  exports.prototype.flAtivo = undefined;

  /**
   * @member {String} nmInteressado
   */
  exports.prototype.nmInteressado = undefined;

  /**
   * @member {String} nuIdentificacao
   */
  exports.prototype.nuIdentificacao = undefined;


  return exports;

}));
