/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ApiDocumentation) {
      root.ApiDocumentation = {};
    }
    root.ApiDocumentation.ProcessoDTOInput = factory(root.ApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ProcessoDTOInput model module.
   * @module model/ProcessoDTOInput
   * @version 1.0
   */

  /**
   * Constructs a new <code>ProcessoDTOInput</code>.
   * @alias module:model/ProcessoDTOInput
   * @class
   * @param cdAssuntoId {Number} 
   * @param cdInteressadoId {Number} 
   * @param descricao {String} 
   * @param nuAno {String} 
   * @param sgOrgaoSetor {String} 
   */
  var exports = function(cdAssuntoId, cdInteressadoId, descricao, nuAno, sgOrgaoSetor) {
    this.cdAssuntoId = cdAssuntoId;
    this.cdInteressadoId = cdInteressadoId;
    this.descricao = descricao;
    this.nuAno = nuAno;
    this.sgOrgaoSetor = sgOrgaoSetor;
  };

  /**
   * Constructs a <code>ProcessoDTOInput</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProcessoDTOInput} obj Optional instance to populate.
   * @return {module:model/ProcessoDTOInput} The populated <code>ProcessoDTOInput</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('cdAssuntoId'))
        obj.cdAssuntoId = ApiClient.convertToType(data['cdAssuntoId'], 'Number');
      if (data.hasOwnProperty('cdInteressadoId'))
        obj.cdInteressadoId = ApiClient.convertToType(data['cdInteressadoId'], 'Number');
      if (data.hasOwnProperty('descricao'))
        obj.descricao = ApiClient.convertToType(data['descricao'], 'String');
      if (data.hasOwnProperty('nuAno'))
        obj.nuAno = ApiClient.convertToType(data['nuAno'], 'String');
      if (data.hasOwnProperty('sgOrgaoSetor'))
        obj.sgOrgaoSetor = ApiClient.convertToType(data['sgOrgaoSetor'], 'String');
    }
    return obj;
  }

  /**
   * @member {Number} cdAssuntoId
   */
  exports.prototype.cdAssuntoId = undefined;

  /**
   * @member {Number} cdInteressadoId
   */
  exports.prototype.cdInteressadoId = undefined;

  /**
   * @member {String} descricao
   */
  exports.prototype.descricao = undefined;

  /**
   * @member {String} nuAno
   */
  exports.prototype.nuAno = undefined;

  /**
   * @member {String} sgOrgaoSetor
   */
  exports.prototype.sgOrgaoSetor = undefined;


  return exports;

}));
